name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Install Gradle
      run: |
        wget https://services.gradle.org/distributions/gradle-7.6-bin.zip
        unzip gradle-7.6-bin.zip
        export PATH=$PATH:$PWD/gradle-7.6/bin
    - name: Setup Gradle Wrapper
      run: |
        echo "org.gradle.jvmargs=-Xmx2g" > gradle.properties
        gradle wrapper --gradle-version 7.6
        chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDebug
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
