jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Check working directory
      run: pwd

    - name: List files in gradle/wrapper
      run: ls -la gradle/wrapper || echo "Directory not found"

    - name: Set permissions for gradle-wrapper.jar
      run: if [ -f gradle/wrapper/gradle-wrapper.jar ]; then chmod 644 gradle/wrapper/gradle-wrapper.jar; fi

    # Aquí irían el resto de tus pasos...
    # Aquí irían el resto de tus pasos...
