name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - name: Accept Android SDK Licenses
      run: yes | sdkmanager --licenses
    - name: Install Gradle
      run: |
        wget https://services.gradle.org/distributions/gradle-7.6.3-bin.zip
        unzip gradle-7.6.3-bin.zip -d /opt/gradle
        export PATH=$PATH:/opt/gradle/gradle-7.6.3/bin
    - name: Initialize Gradle Wrapper
      run: gradle wrapper --gradle-version 7.6.3
    - name: Accept Gradle Terms
      run: echo "org.gradle.jvmargs=-Xmx2g" > gradle.properties && echo "android.enableJetifier=true" >> gradle.properties && gradle --version --no-daemon
    - name: Make Gradle Executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDebug --stacktrace --info --scan
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
